export const MAX_AIRPORT_ALLOWED = 3;

export const SEARCH_AIRFIELD_REQUEST = "SEARCH_AIRFIELD_REQUEST";
export const SEARCH_AIRFIELD_SUCCESS = "SEARCH_AIRFIELD_SUCCESS";
export const SEARCH_AIRFIELD_FAILURE = "SEARCH_AIRFIELD_FAILURE";

export const CLEAR_AIRFIELD_REQUEST = "CLEAR_AIRFIELD_REQUEST";
